import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, existsSync, mkdirSync } from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
PARA Kanban — a kanban Bases view for Obsidian.
Fork of github.com/xiwcx/obsidian-bases-kanban (MIT).
*/
`;

const prod = process.argv[2] === 'production';

// Both dev and prod emit into dist/. CI attaches dist/{main.js,manifest.json,
// styles.css} to the GitHub release (the layout BRAT reads). Set PARA_KANBAN_OUT
// to a vault plugin folder to also copy the built files there for local testing.
const outDir = 'dist';
const installDir = process.env.PARA_KANBAN_OUT || null;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2020',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${outDir}/main.js`,
});

if (prod) {
	await context.rebuild();

	if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
	copyFileSync('manifest.json', `${outDir}/manifest.json`);
	copyFileSync('styles.css', `${outDir}/styles.css`);

	// Optional: also install into a vault plugin folder for quick local testing.
	if (installDir) {
		if (!existsSync(installDir)) mkdirSync(installDir, { recursive: true });
		copyFileSync(`${outDir}/main.js`, `${installDir}/main.js`);
		copyFileSync('manifest.json', `${installDir}/manifest.json`);
		copyFileSync('styles.css', `${installDir}/styles.css`);
	}

	process.exit(0);
} else {
	await context.watch();
}
